### ISSUE TITLE
Issue with tags generation

### ISSUE THREAD

**Issue by Moinax** [open-template-hub/swagger-decorators#20]
<p align="center"><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo-broken.png" alt="Logo" width=150></a></p>
<h2 align="center">Open Template Hub - Bug Report</h2>

## Description

I tried to build your example, but I got an issue reading the generated swagger file.

The generate `tag/index.swagger.tag.ts` is spreading the tags as an `object` while it's actually an `array`

```
import { MyRouteTags } from "./myroute.swagger.tag";

export const allTags = {
  ...MyRouteTags,
};
```

If I manually change the content of this file to

```
import { MyRouteTags } from "./myroute.swagger.tag";

export const allTags = [
  ...MyRouteTags,
];
```

Then I can serve the swagger file with `swagger-ui-express` as shown in your example.

But otherwise I get an error message

```
/docs/swagger/index.swagger.ts:42
    tags: [...allTags],
              ^
TypeError: index_swagger_tag_1.allTags is not iterable
    at new SwaggerSpec (/home/moinax/WebstormProjects/mbrella/public-client/docs/swagger/index.swagger.ts:42:15)
    at Object.<anonymous> (/home/moinax/WebstormProjects/mbrella/public-client/src/docs/serve.ts:4:30)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/moinax/WebstormProjects/mbrella/public-client/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/moinax/WebstormProjects/mbrella/public-client/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/home/moinax/WebstormProjects/mbrella/public-client/node_modules/ts-node/src/bin.ts:649:14)
```

I believe the issue comes from the fact that you use the same [index.template](https://github.com/open-template-hub/swagger-decorators/blob/develop/lib/template/index.template) for all of them, which works perfectly fine except for the tags, because they are not an object like the others, but an array.

<table align="right"><tr><td><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo.png" width="50px" alt="oth"/></a></td><td><b>Open Template Hub © 2023</b></td></tr></table>

**Comment by fatihturker** [comment]
Hi @Moinax ,

We sincerely appreciate your valuable contribution to the package, including opening the issue and providing the pull request. As a token of our gratitude, we have added you to our esteemed list of contributors.

Best Regards,
Fatih
